### PR TITLE
Vasil/Babbage network support

### PR DESCRIPTION
**Pull request by ryukzak**
- [x] Added docker-compose for up&running Vasil test network
- [x] Add support for BabbageBlock
- [x] Improved warning messages
- [x] Get inlined datum (https://github.com/cardano-foundation/CIPs/tree/master/CIP-0032)

Related ogmios issue: https://github.com/CardanoSolutions/ogmios/issues/215

### CODE REVIEW

**Comment by KtorZ** [comment]
( https://github.com/CardanoSolutions/ogmios/pull/220 )

**Review by t4ccer — COMMENTED** [review]
I'm not sure if it's worth it to keep separate types for alonzo and babbage stuff, as you can reuse babbage types in alonzo and just set datum to `Nothing` (as it's the only difference). At the same time we maybe shouldn't care because we want to reuse ogmios defined types. We need to establish some merging schedule wrt. my backend PR

**Comment by ryukzak** [comment]
The origin of ideas about separated types is ogmios and ouroboros-consensus-cardano, but in our limited use case, we can merge them without visible for me problems.

About usage of ogmios type -- if we don't expand ODC features, it should create more problems than solves because we will need to manage a lot of new dependencies.

I think your backend rework should be merged first because here should be much simpler to fix merge conflicts. At the same time, I will merge block types as you propose.

**Review by t4ccer — COMMENTED** [review]
Have you also tested that it works well on Alonzo?

**Comment by ryukzak** [comment]
@t4ccer It is not required, because we fetch both types of transactions from the ogmios. 

In a naive way, something was broken from the last updates. Work on it.

**Pull request merged**
